package by.epamtc.final_task.controller.constant;

public class ParameterName {
    public static final String ADD_FOR_PATH_AVATAR = "/";
    public static final String AVATAR = "avatar";
    public static final int ERROR_NOT_FOUND = 404;
    public static final String AUTHOR_ID = "authorId";
    public static final String CHANGE_ROLE = "changeRole";
    public static final String CHANGE_ROLE_ERROR = "changeRoleError";
    public static final String COMMAND = "command";
    public static final String COMMENT = "comment";
    public static final String COURSE = "course";
    public static final String COURSE_CANCEL = "courseCancel";
    public static final String COURSE_LIST = "courseList";
    public static final String COURSE_RUN_COMMAND = "courseruncommand";
    public static final String COURSE_TITLE = "courseTitle";
    public static final String COURSE_ID = "courseId";
    public static final String COURSES_COUNT = "coursesCount";
    public static final String CREATE_MESSAGE = "createMessage";
    public static final String CURRENT_PAGE = "currentPage";
    public static final String CURRENT_PAGE_AFTER_REDIRECT = "currentPageAfterRedirect";
    public static final String DESCRIPTION = "description";
    public static final String EDIT_COURSE_RESULT="editCourseResult";
    public static final String EMAIL = "email";
    public static final String EN = "en";
    public static final String END="end";
    public static final String ERROR = "error";
    public static final String ERROR_CANCEL_COURSE = "errorCancelCourse";
    public static final String ERROR_MESSAGE_404 = "Page not found";
    public static final String FIRST_NAME = "first_name";
    public static final String FORMAT ="format";
    public static final String INCORRECT_ERROR_PASSWORDS = "registrationErrorPasswords";
    public static final String INCORRECT_ERROR_SYMBOLS = "registrationErrorSymbols";
    public static final String INCORRECT_LOGIN_AND_PASSWORD = "errorLoginPassMessage";
    public static final String INIT_DETAILS_COURSE_COMMAND = "detailscourse";
    public static final String LAST_NAME = "last_name";
    public static final String LANGUAGE = "language";
    public static final String LANGUAGE_CHANGED = "language_changed";
    public static final String LANG_CHANGE_PROCESS_COMMAND = "langChangeProcessCommand";
    public static final String LECTURER_ID = "lecturerId";
    public static final String LIMIT_STUDENTS = "limitStudents";
    public static final String LOCALE_EN = "EN";
    public static final String LOCALE_RU = "RU";
    public static final String LOGIN_COMMAND="login";
    public static final String MARK = "mark";
    public static final String NAME_LECTURER = "nameLecturer";
    public static final String NOT_REGISTER_ON_COURSE = "listCoursesIsEmpty";
    public static final String PAGE = "page";
    public static final String CURRENT_NAV_LOCALE ="currentNavLocal";
    public static final String PASSWORD = "password";
    public static final String PHOTO_PATH = "photo_path";
    public static final String REDIRECTED_PAGE = "redirectedPage";
    public static final String REGISTER_COURSE_MESSAGE = "registerMessage";
    public static final String REGISTER_COURSE_ERROR = "registerMessageError";
    public static final String REGISTRATION_ERROR = "registrationError";
    public static final String REGISTRATION_OK = "registrationOk";
    public static final String REPEAT_PASSWORD = "repeat password";
    public static final String ROLE = "role";
    public static final String RU = "ru";
    public static final String START = "start";
    public static final String STATUS_COURSE = "statusCourse";
    public static final String STATUS_USER = "statusUser";
    public static final String SURNAME_LECTURER = "surnameLecturer";
    public static final String TITLE = "title";
    public static final String UPLOAD_DIR_FOR_USER_AVATAR = "C:\\Users\\Кузьменко\\IdeaProjects\\final-task\\src\\main\\webapp\\images\\picturesForAvatar\\";
    public static final String UPLOAD_RESULT = "uploadResult";
    public static final String USER = "user";
    public static final String USERS_COUNT = "usersCount";
    public static final String USER_ID = "user_id";
    public static final String USER_LIST = "userList";
    public static final String VIEW_USERS_ERROR = "viewUsersError";
    public static final String WELCOME = "welcome";

    private ParameterName() {
    }
}
