package by.epamtc.final_task.controller.command;

/**
 * The enum Command type.
 */
public enum CommandName {

    COURSERUNCOMMAND,
    COURSESPAGE,
    COURSESLECTURER,
    CREATECOURSE,
    DETAILSCOURSE,
    EDITPROFILECOMMAND,
    EDITCOURSE,
    EMPTY,
    FORWARD,
    FORWARDTOEDITCOURSE,
    FORWARDTOSETRESULT,
    INITPROFILECOMMAND,
    INITTABLEUSERSCOMMAND,
    INITTABLEUSERSONCOURSE,
    LANGUAGE,
    LOGIN,
    LOGOUT,
    REGISTRATION,
    SETCOURSERESULT,
    VIEWCOURSESUSER
}
