package by.epamtc.final_task.controller.command;

public enum CommandName {

    COURSERUNCOMMAND,
    COURSESPAGE,
    CREATECOURSE,
    DETAILSCOURSE,
    EDITPROFILECOMMAND,
    EDITCOURSE,
    FORWARD,
    FORWARDTOCREATECOURSE,
    FORWARDTOEDITCOURSE,
    FORWARDTOEDITPROFILE,
    FORWARDTOSETRESULT,
    FORWARDWELCOME,
    INITPROFILECOMMAND,
    INITTABLEUSERSCOMMAND,
    INITTABLEUSERSONCOURSE,
    LANGUAGE,
    LOGIN,
    LOGOUT,
    REGISTRATION,
    SETCOURSERESULT,
    VIEWCOURSESUSER;
}
